language: objective-c
xcode_workspace: "Traffic Buddy.xcworkspace"
xcode_scheme: "Traffic Buddy"
osx_image: xcode9

script: xcodebuild clean && xcodebuild build -workspace "Traffic Buddy.xcworkspace" -scheme "Traffic Buddy" -allowProvisioningUpdates
